/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gingerjake.toolbox;

import javax.swing.*;
import java.awt.*;

public class Main {

    public static void main(String[] args) {

        JFrame MainWindow = new JFrame("Test");
        MainWindow.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        JPanel Display = new JPanel();

        MainWindow.add(Display);
        Display.add(new Display(), BorderLayout.CENTER);
        MainWindow.pack();
        MainWindow.setVisible(true);

        System.out.println("Don't wanna be an American Idiot,");
        System.out.println("One nation under the new media...");
        System.out.println("And can you hear the sound of hysteria?");
        System.out.println("It's calling out to Idiot America!");

    }
}
